= Tooltip Guides

Use the following guidance to write text for a Tooltip Guide. 

A Tooltip can be either:

* <<additional,An Additional Information Tooltip>>: Provide a user with additional information about an element in the UI.
* <<prereq,A Prerequisite Tooltip>>: Direct a user to another location in the UI to complete a Prerequisite task. 

[#additional]
== Additional Information Tooltips 

Additional Information Tooltips should only contain <<add-body,body text>>.

=== Title

Don't add a title to Additional Information Tooltips.

[#add-body]
=== Body Text

In the body text for an Additional Information Tooltip: 

|====
|Description  | Do | Don't

| Avoid lengthy explanations for the target UI element. 
If you find yourself going over more than 2 short paragraphs, rethink the Tooltip.
a| * *Provisioned*: Have greater control over your deployment, with features designed for heavier workloads. 

* *Serverless*: Let Couchbase manage your deployment while you focus on development. 
| Use a Provisioned database to manage all aspects of your Couchbase Capella database deployment. You can choose the combination of nodes and services that suits your workload needs, as well as the support plan you need for your database. Use a Serverless database to let Couchbase manage most aspects of your deployment for you.

| Use *Learn More* links to give the user additional context and explanation through the documentation.
| Use a project to organize the databases in your organization. xref:tooltips.adoc[Learn More]
| Projects organize and control access to databases and App Services in your organization.
You can view the projects available to you on the *Projects* tab. 
You can create a project if you have the *Project Creator* or *Organization Owner* role. 
If you don't have the *Project Creator* or *Organization Owner* role, you can only access and create databases and App Services in existing projects in your organization. 
|====

=== Action Button

Don't add an action button to Additional Information Tooltips. 

Users can close or dismiss the Tooltip with the Close icon (x). 

[#prereq]
== Prerequisite Tooltips

Prerequisite Tooltips should contain: 

* <<prereq-title,A title>>
* <<prereq-body,Body text>> 
* <<prereq-action,An action button>>

[#prereq-title]
=== Title

|====
|Description |Do |Don't

|Write the title as an imperative phrase, starting with an action verb. 
a| Set bucket, scope, and access

Configure database access credentials 
a| Buckets, scopes, collections 

Query Context 

|Write in sentence case, but match capitalization of named UI elements.
a| Set Query Context

Add a new bucket
a|Add Your Database Access Credentials 

Add api key and secret

| Don't use any other punctuation aside from commas, where needed.
a| Set database name and region

Get API Key, API Secret, and API endpoint
a| Set your database name! 

Are you sure you want to continue?
|====

[#prereq-body]
=== Body Text 

In the body text for a Prerequisite Tooltip:

|====
|Description |Do |Don't

|Avoid lengthy explanations about the how and why for the Tooltip.
Stick to 1 or 2 sentences.
| To create a database, you need to create a project. 
| You need to create a project before you can create a database. All databases in Capella need to exist inside a project. You can select an existing project from the list, or you can go to the *Projects* tab to create a new project. 

|Clearly state the goal or benefit to the user, followed by where the Tooltip will take them in the UI. 
| To connect to your database, go to *Database Access* and add database access credentials.
| Click *Let's go!* to connect to your database.

|Use *Learn More* links to give the user additional context and explanation through the documentation. 
| To create an App Service, create a compatible database. xref:tooltips.adoc[Learn More]
| You don't have any compatible databases where you can create an App Service. You need to create a database to create an App Service. The database must have the Data, Index, and Query services. It must have at least one bucket, and not have an App Service currently linked to it. 

|Use *bold* to emphasize UI element names. 
| *Database Access*
| _Database Access_

|====

[#prereq-action]
=== Action Button 

Prerequisite Tooltips must have an action button. 

The action button should always say *Let's go!*. 

Above the action button, make sure you add a code block with the following JavaScript, replacing the variables with the appropriate values:

[source,javascript]
----
if(!pendo.designerEnabled){
function getUrl(url) {
  // Get the query string from the current URL
  const queryParams = window.location.search;

  // Append the query string to the specified URL, and add an optional permalink to another Pendo Guide at the destination URL
  const newUrl = url + queryParams + '$OPTIONAL_PENDO_PERMALINK';

  // Open the new URL in a new window
  window.open(newUrl, '_blank');
}

// Replace $PARTIAL_URL with everything after https://cloud.couchbase.com/, stopping before the ? in the URL you want to go to
pendo.dom('._pendo-button-primaryButton')[0].addEventListener("click", function () {
    	getUrl('$PARTIAL_URL');
});
}
----