= Create a Free Account and Deploy Your Database
:page-topic-type: tutorial
:description: Create a Couchbase Capella account to start using Capella to manage your data.
:page-aliases: create-app-services-account.adoc, get-started.adoc
:page-pagination:

[abstract]
{description}

To get started, you can use a Couchbase Capella Free Trial.

[#sign-up-free-trial]
== Create a Free Account

. In your web browser, go to the https://cloud.couchbase.com/sign-up[Couchbase Capella Sign-up page].

. In the *Full Name* field, enter your full name. 

. In the *Email Address* field, enter the user address you want to use to login to your Capella account. 

. In the *Password* field, enter a password for your Capella account.
+
[NOTE]
====
Your password must:

* Contain at least eight characters.
* Contain uppercase characters (A-Z).
* Contain lowercase characters (a-z).
* Contain numbers (0-9). 
* Contain special characters, such as @, #, or $.
====

. Click *[ Get Started ]*. 
+
Couchbase sends an email to your provided email address with a confirmation code for your account. 

. Enter the code from the email into the provided field. 

. Review and agree to the https://www.couchbase.com/CapellaCSSA10192021[Terms of Service^] and https://www.couchbase.com/privacy-policy[Privacy Policy^]. 

. (Optional) To subscribe to email updates from Couchbase, click *I agree to be updated on offers, products, and services from Couchbase*. 

. Click *[ Create Account ]*.

NOTE: After you <<sign-up-free-trial,>>, you can upgrade your account with an Activation ID from Couchbase Sales.
To access all features of Couchbase Capella, xref:manage-billing.adoc#add-activation-id[Add an Activation ID] to your account.


[#getting-started]
== Deploy Your Database

After you create your account, answer some questions to customize your Capella experience and deploy your database. 

. In the *Preferences* section, do one of the following: 
+
* To set your Preferences, select one or more options for your expected use of Capella and your experience level with Couchbase. Click *[ Next ]*.
* To skip setting any Preferences, click *[ Skip ]*.

. In the *Languages* section, do one of the following: 
+
* To set a preferred programming language, select one or more of the programming languages you want to use with Capella. Click *[ Next ]*.
* To skip selecting a preferred programming language, click *[ Skip ]*.

. In the *Database Name* field, enter a name for your database or accept the default. 

. Select an available cloud provider: 
+
* *AWS*
* *Google Cloud*
+
For more information about the available cloud providers for Capella, see xref:aws.adoc[] or xref:gcp.adoc[].

. Select an available geographic region for your database or accept the default. 
+
For more information about the supported regions for Capella, see xref:aws.adoc[] or xref:gcp.adoc[].

. (Optional) In the *CIDR Block* field, enter a range of IP addresses in CIDR notation for your database or accept the default. 

. Click *[ Deploy Now ]*.
+
Capella deploys your database with your chosen settings.

[#app-services]
== Deploy Your App Services Trial 

You can use Capella App Services to sync data between Capella buckets and mobile or edge devices running xref:couchbase-lite:ROOT:index.adoc[Couchbase Lite]. 
You can also use it to authenticate and manage mobile and edge users. 

To deploy an App Services trial for mobile development: 

. From the *Start* page, click *[ Link App Service ]*. 
+
Capella starts to deploy your App Service. 
The process takes a few minutes to complete.

For more information about how to configure App Services, see xref:configuring-app-services.adoc[].

== Next Steps

After you deploy your database, you can xref:run-first-queries.adoc[] and xref:sdk-playground.adoc[].

You can also xref::import-data-documents.adoc[Import your own data] and xref:configuring-app-services.adoc[Configure App Services for your trial database].

include::partial$connect-database-next-steps.adoc[]


