= Data Service

[abstract]
The Data Service provides access to data.
It supports the storing, setting, and retrieving of data-items, specified by key.

The _Data Service_ is the most fundamental of all Couchbase services, providing read/write access to data in memory and on disk.
The Data Service stores data items in _Buckets_.
Before an item can be saved, a bucket must exist for it.
Buckets only exist on nodes that run the Data Service.


== Deploying the Data Service

The Data Service must run on at least one node of every cluster.
However, at least three nodes are required for production environments.
(Clusters with less than three Data nodes have xref:server:install:deployment-considerations-lt-3nodes.adoc[several limitations].)

The Data Service provides a fully integrated in-memory caching layer, which provides high-speed data access.
Couchbase Capella supports the xref:server:learn:buckets-memory-and-storage/buckets.adoc#bucket-types[_Couchbase_ bucket type], which means that all data items are written to memory and persisted to disk.
The Data Service manages memory to ensure high performance and scalability: memory quotas are established, and data not recently used can be ejected, to make room for data more frequently requested.
You can configure a memory quota that provides caching for all or a portion of stored data items.

Read more about xref:server:learn:buckets-memory-and-storage/memory-and-storage.adoc[Memory and Storage].


== Buckets

Couchbase Server uses buckets to group collections of keys and values logically.
Buckets must be created before you can store any data.
A maximum of 30 buckets can be created per cluster.

Buckets are protected by role-based access control (RBAC).
Buckets can only be administered (created, modified, and deleted) by users that have the xref:projects:project-roles.adoc#project-owner-role[`Project Owner`] or xref:projects:project-roles.adoc#project-cluster-manager-role[`Project manager`] project roles.


== Scopes and Collections 

Couchbase Server uses scopes and collections to categorize and organize documents within a bucket. 
Collections are data containers within a bucket, while scopes are mechanisms to group multiple collections. 
Each cluster can have up to 1000 scopes and 1000 collections. 

Every bucket automatically includes the `_default` scope that itself contains the `_default` collection. 
Any document that is created within a bucket that does not reference a scope or collection is saved in the default collection within the default scope. 
You cannot drop default scopes, and you may only drop default collections using the Couchbase Capella API, SDKs, or queries. 
You cannot recreate a default collection if you drop it. 

Role-based access control (RBAC) is used to protect scopes and collections. 
Only project members with the xref:projects:project-roles.adoc#project-owner-role[`Project Owner`] or xref:projects:project-roles.adoc#project-cluster-manager-role[`Project manager`] project roles can administer them.
  
For more information, see xref:server:learn:data/scopes-and-collections.adoc[Scopes and Collections].