= General UI Copy Principles

The following are some general principles for UI copy in the Couchbase Style: 

* <<lowest,Write for the Lowest Common Denominator>>
* <<critical,Explain What's Critical>>
* <<can-do,Focus on What the User Can Do>>
* <<short,Keep It Short and Simple>>
* <<consistent,Keep It Consistent>>
* <<numbers,Don't Write Out Numbers>>
* <<sentence,Use Sentence Case>>

For an overview of voice and tone, see xref:styleguide:ROOT:tone.adoc[] in the Couchbase Documentation Style Guide.

[#lowest]
== Write for the Lowest Common Denominator 

The golden rule for when to add UI copy or text is simple:

If a lower-level user would struggle or the required action isn't obvious, add the text.

We want our UI to be accessible to all users and should always aim to add text to reduce friction. 

[#critical]
== Explain What is Critical 

Keep to the most critical and important information when adding UI copy. 

Lengthy explanations or unusual situations should be explained in the documentation, not the UI. 

[#can-do]
== Focus on What the User Can Do 

When writing an xref:error-messages.adoc[error message] or any kind of text guiding a user away from an action, don't reveal or focus on their lack of permissions. 

Focus on what the user can do in their current situation, unless there's no other option than to ask an administrator about their permissions.

[#short]
== Keep It Short and Simple 

Always write in full and complete sentences outside of headings. 

Keep text short and to the point. 

[#consistent]
== Keep It Consistent 

Keep the terminology that you use consistent across the UI. 

What's called a cluster in one part of the UI shouldn't be called a database elsewhere. 

[#numbers]
== Don't Write Out Numbers 

Unlike technical documentation, UI copy should always use numerals for ease of recognition. Use 3 over three. 

Also aim to add units of measurement for numbers, where applicable. 

[#sentence]
== Use Sentence Case

Use sentence case capitalization for UI text.

Use title case only for xref:action-buttons.adoc[buttons].

Headings should be in sentence case. 

In general, find another visual way to add emphasis to text.