= Bold

Use bold to format UI elements, such as: 

* Single menu items 
* Tab names 
* Dialog names

Surround a word or phrase with asterixes (*) to make it render as bold in Antora. 
For more information, see https://docs.couchbase.com/home/contribute/basics.html#bold-italic-and-code-styles[Bold, Italic, and Code Styles] in the Contributing to the Documentation guide.

If the UI element is: 

* a button,
* a series of menu navigation instructions,
* a keyboard interaction,

use the appropriate macro, instead. 

== Buttons, Menus, and Keyboard Keys

To emphasize and make menu navigation stand out in your text, use the Menu UI Macro. 
For more information, see xref:menu-ui-macro.adoc[].

To emphasize buttons and make them stand out in your text, use the Button Macro. 
For more information, see xref:button-macro.adoc[].

To emphasize keyboard shortcuts and other keyboard interactions in your text, use the Keyboard Macro. For more information, see xref:keyboard-macro.adoc[]

For more information about how to use the `btn:[]`, `menu:[]`, and `kbd:[]` macros, see https://docs.couchbase.com/home/contribute/basics.html#ui-macros[Button, Keyboard, and Menu UI Macros] in the Contributing to the Documentation guide.