= Headings

Use headings to split up the content on a page and make it easier for a user to scan. A heading indicates what information a user finds in a specific section of the page. 

NOTE: This guidance applies only to H<n> elements. For guidance on captions for images and tables, see xref:images-diagrams.adoc[Images] and xref:tables.adoc[Tables], respectively.

Use the following guidance to write headings in your topics: 

Capitalization:: Use title case for all headings: 
+
* Always capitalize the first word. 
* Capitalize the main nouns, verbs, and adjectives. 
* Leave articles, coordinating conjunctions, prepositions and other connecting words in lower case (and, the, to). 
+
This matches the Chicago Manual of Style. Vale flags any heading capitalization that doesn't match the Chicago style.
Length:: Try to keep headings as short and to-the-point as possible. Try to fit your heading in a single line. 
Frequency:: Use a heading whenever it makes sense to do so - usually when you're starting a new thought or need to highlight something new and important to the user. Keep headings useful, and make sure that you always have content in between two headings. Vale flags any headings that appear directly on top of each other with no content in between. 
Depth:: Do not go past an H4 heading in your text. You don't need to have more than 4 levels of headings in your text. 

The content of your H1 heading also needs to match the type of topic you're writing: 

|===
| Content Type | Heading Style | Examples

|Concept topic
|Concept headings are a single noun, which accurately outlines the concept you're describing. Use additional words if you feel that a single noun can't accurately describe the content of the page. 
a| Clusters

Indexes

|Task topic
|Task headings are short imperative phrases that start with a verb that does something to a noun. 
a|Delete a Cluster

Create an Index

Explore Your Data

|Reference topic
|Reference headings are short phrases that state what kind of reference content the user finds on a page. ##Does the heading need to include the word "reference"?## 
a| Audit Events

Error Messages 

Rebalance Reports

|===