= Writing Procedures

A procedure can be: 

A how-to guide :: How-to guides explain to the user how to accomplish a goal without a specific, defined end result. The specifics of the end result will vary depending on the individual user's goal. For example, a how-to guide could explain how to create a database by explaining the different options and customizations the user can make. 
A tutorial :: Tutorials explain to the user how to accomplish a goal that has a defined end result. All users that follow the tutorial will have the same result. For example, a tutorial could explain how to create a specific kind of database that would support a specific use case for the user. 

== Description Attribute

Before the <<prerequisites,Prerequisites section>>, you should have a brief explanation of the goal of the procedure, or what the user can hope to accomplish once they've completed the procedure. 

This goal should be part of the `:description:` attribute that you need to add to the beginning of every topic. 

If you need to add links to your brief explanation, put them outside of the `:description:` attribute. 

== Required Sections

All procedures should contain 3 section headers: 

. <<prerequisites,Prerequisites>> 
. <<procedure,Procedure>>
. <<next-steps,Next Steps>> 

[#prerequisites]
=== Prerequisites 

The *Prerequisites* section should be an H2 level heading. 

It contains an xref:unordered-list.adoc[unordered list] of things the user must do or have before they can proceed with the content in <<procedure,Procedure>>. 

NOTE: There will always be something the user can do.

Add links where appropriate, following the appropriate xref:links.adoc[link formatting guidance].

[#procedure]
=== Procedure

The *Procedure* section should be an H2 level heading that follows the <<prerequisites,Prerequisites section>>.

It contains an xref:ordered-list.adoc[ordered list] of steps the user must take to complete the specific goal of the page. 

Steps in a *Procedure* section should: 

* List only one action per step, with the exception of using an xref:menu-ui-macro.adoc[] for menu navigation steps.
* Start with the location where the following action or actions need to occur.
This could be the start of the step, or the start of the procedure itself, with menu navigation.
* Use xref:button-macro.adoc[button macros] for all xref:buttons.adoc[].
* Use xref:keyboard-macro.adoc[keyboard macros] for all keyboard interactions.
* Use xref:monospace-highlight.adoc[monospace font] for all code outside of code blocks, SQL++ commands, function names, file paths, filenames, and text the user must input.
* Use xref:bold.adoc[] for single menu items, tab names, and dialog names.

Steps in a *Procedure* section shouldn't: 

* List the result of an action, if the result is obvious.
For example, the *Create Project* window appears after you click *Create Project*. 
* Contain lengthy explanations for the reason behind a step. 
Link to explanatory documentation, such as a concept, where necessary. 

[#next-steps]
=== Next Steps 

The *Next Steps* section should be an H2 level heading that follows the <<procedure,Procedure section>>.

It contains either an: 

* xref:unordered-list.adoc[Unordered list] of links.
* Running text that describes the next procedure or action the user can take.

The *Next Steps* section is where additional procedures in a series or links to additional reading on other documentation pages should live. 

Always add links to a *Next Steps* section. 

Don't call the section *See Also*, *Additional Resources*, or similar. 
There's always some action the user can take after they complete a procedure. 